import type {Metadata} from "next";
import "./globals.css";
import {cookies} from "next/headers";
import {geistMono, geistSans} from "./assets/fonts/fonts";
export const metadata: Metadata = {
    title: {
        template: "%s | Note Taking App",
        default: "Note Taking app",
    },
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let fontCookie = (await cookies()).get("n-t-a-f");
    let value = fontCookie?.value;
    return (
        <html lang="en">
            <body
                className={` ${geistMono.className} ${geistSans.className} ${value} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
